language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

after_success:
  - mvn -DrepoToken=$COVERALLS_TOKEN jacoco:report coveralls:report
